# This is a job based template which will simply always succeed after waiting
# for 3 minutes. Which can be useful for testing e.g. abort logic.
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: test
  namespace: kargo-advanced
spec:
  metrics:
    - name: test
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - name: test
                    image: alpine:latest
                    command: [sh, -c]
                    args: ["sleep 180; exit 0"]
                restartPolicy: Never
